language: node_js
node_js:
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
  - "5"
  - "6"
before_install:
  - ./update_apt
  - sudo apt-get install zookeeper
  - sudo apt-get install zookeeperd
before_script:
  - sudo /etc/init.d/zookeeper start
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
after_script: ZK_NO_WARN=true istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

